config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts
  resources :users, only: [:show]
    get 'users/:id/sightings' => 'users#sightings'
    get 'users/:id/posts' => 'users#posts'
  resources :sightings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :sighting
    mount_uploader :url, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  # has_one_attached :image
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :name, presence: true
  validates :lost_place, presence: true
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  after_validation :reverse_geocode, if: ->(obj){ obj.latitude.present? and obj.latitude_changed? }

  def image_filename
    self.image.filename.to_s if self.image.attached?
  end

  def image_url
    self.image.url
  end
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  require "google/cloud/vision"
  # has_one_attached :image
  # has_many :images
  mount_uploader :image, ImageUploader
  belongs_to :user
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  validates :place, presence: true
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  after_validation :reverse_geocode, if: ->(obj){ obj.latitude.present? and obj.latitude_changed? }

  # def image_filename
  #   self.image.filename.to_s if self.image.attached?
  # end

  # def image_url
  #   url_for(self.image) if self.image.attached?
  # end

  def cat?
    labels = []
    labelText = ""
    project_id = "tigrasha"
    image_annotator = Google::Cloud::Vision::ImageAnnotator.new
    file_name = self.image.url
    response = image_annotator.label_detection image: file_name
    response.responses.each do |res|
      puts "Labels:"
      res.label_annotations.each do |label|
        puts label.description
        labels << label.description
        labelText += (label.description + ": " + label.score.to_s + "\n")
      end
      
      if labels.include?("Cat")
        labelText += "かわいいネコちゃんですね！"
      else
        labelText += "ネコじゃないよね？"
      end
    end

    return labelText
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :sightings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def create
        @image = Image.new(image_params)
        binding.pry
        @image.save
    end

    private

    def image_params
        params.requre(:image).permit[:url]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :new, :create]

  def index
    @posts = Post.includes(:user)
  end

  def show
    @sightings = Sighting.near([@post.latitude, @post.longitude], 5)

    respond_to do |format|
      format.html
      format.js
      format.json {render json: @sightings}
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.js {render json: @post}
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      respond_to do |format|
        format.js {render json: @post}
      end
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :name, :lost_place, :lost_date, :address, :latitude, :longitude, :detail).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting

  def index
    if params[:sighting].present?
      @sightings = Sighting.ransack(place_or_detail_or_address_matches: "%#{params[:sighting][:keyword]}%").result

      render @sightings
    end
  end

  def show
    @sighting = Sighting.find(params[:id])
    @labels = @sighting.cat?
  end

  def new
  end

  def create
    @sighting = Sighting.new(sighting_params)
    if @sighting.save
      respond_to  do |format|
        format.js {render json: @sighting}
      end
    else
      render :new
    end
  end

  def update
    @sighting = Sighting.find(params[:id])
  end

  def destroy
    @sighting = Sighting.find(params[:id])
    @sighting.destroy

    respond_to do |format|
      format.html
      format.json {render json: @sighting, only: ["id"]}
      format.js {render json: @sighting, only: ["id"]}
    end
  end

  private

  def sighting_params
    params.require(:sighting).permit(:detail, :image, :place, :date, :address, :latitude, :longitude).merge(user_id: current_user.id)
  end

  def image_params
    params.requre(:image).permit[:url]
  end

  def set_sighting
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(current_user.id)
  end

  def sightings
    user = User.find(current_user.id)
    @sightings = user.sightings

    render @sightings
  end

  def posts
    user = User.find(current_user.id)
    @posts = user.posts

    render @posts
  end

  def new
  end

  def destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-gray.fixed-top.navbar__header
  .container
    .anti-button-blank
    .tigrasha.mx-auto.center-block
      %a.navbar-brand.m-0{href: root_path} Tigrasha
    %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    - if user_signed_in?
      #navbarResponsive.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto.navbar__header__list
          .dropdown.nav-item.d-none.d-lg-block
            %a.nav-link.dropdown-toggle#dropdownMenuLink{href: user_path(current_user), "data-toggle": "dropdown", "aria-haspopup": true, "aria-expanded": false} #{current_user.name}
            .dropdown-menu{"area-labelledby": "dropdownMenuLink"}
              = link_to "マイページ", user_path(current_user), class: 'dropdown-item'
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item"
          %li.nav-item
            %a.nav-link{href: posts_path} 張り紙
          %li.nav-item
            %a.nav-link{href: sightings_path} 目撃情報
          %li.nav-item.d-block.d-lg-none
            = link_to "マイページ", user_path(current_user), class: 'nav-link '
          %li.nav-item.d-block.d-lg-none
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"
    - else
      #navbarResponsive.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto.navbar__header__list
          %li.nav-item
            %a.nav-link{href: posts_path} 張り紙
          %li.nav-item
            %a.nav-link{href: sightings_path} 目撃情報
.nav-margin

app/views/layouts/_sidebar.html.haml
.sidebar.bg-light
  .sidebar-sticy
    .ul.nav.flex-column
      .li.nav-item
        = link_to "張り紙", root_path, class: "nav-link"
      .li.nav-item
        = link_to "目撃情報", sightings_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tigrasha
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "//maps.google.com/maps/api/js?key=#{ENV["GOOGLE_MAP_API_KEY"]}&libraries=places"}
  %body
    = yield

-# link_to "/https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.4.3/cropper.css"
-# %script{src: "https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.4.3/cropper.js"}

app/views/posts/_post.html.haml
.col-lg-4.col-md-6.mb-4
  .card.bg-paper.px-3
    %h5.card-title.text-center.mt-2.mb-1.text-danger= post.title
    - if post.image.present?
      = link_to image_tag(post.image.url, class: "img-thumbnail"), post_path(post)
      .card-body
        %p.m-0 場所: #{post.lost_place}
        %p.m-0 お名前: #{post.name}
        %p.m-0 #{post.lost_date.strftime("%Y年 %-m月 %-d日")}

app/views/posts/_trim.html.haml
.modal.modal__trim#trimmingModal{role: "dialog", "data-keyboard": false, "data-backdrop": "static"}
  .modal-content.px-3
    .modal-header
    .modal-body.px-0
      = image_tag "", class: "image-trimming"
    .modal-footer.px-0.py-3
      %button.btn.btn-secondary.btn-trimming-back 戻る
      %button.btn.btn-primary.btn-trimming-confirm 決定

app/views/posts/create.html.haml
.row
  .col-4.text-center.mx-auto
    %h1 張り紙完了！
    %h3 見つかりますように……。

app/views/posts/edit.html.haml
= render "/layouts/navbar"
.bg-image.bg-gray-wall
  .container.container__main{"data-controller": controller_name, "data-action": action_name}
    .row
      .card.col-md-8.mx-auto.my-3.bg-paper
        .card-body
          %h1.text-center 張り紙を編集
          %hr
          - if @post.errors.any?
            .alert.alert-primary.pt-0
              %ul
              - @post.errors.full_messages.each do |message|
                %li= message
          = form_with model: @post, id: "postForm" do |f|
            .form-group
              = f.label :タイトル
              %br/
              = f.text_field :title, class: "form-control", id: "titleField"
            .image-box.text-center.mb-2
              = image_tag @post.image.url, class: "img-thumbnail"
              .image-mask
                = image_tag "no_image_small.png"
            .form-group.hidden.d-none
              = f.label :お写真
              %br/
              = f.file_field :image, class: "form-control-file", id: "imageFile"
            .form-group
              = f.label :お名前
              %br/
              = f.text_field :name, class: "form-control", id: "nameField"
            .form-group
              = f.label :"いなくなった場所・最後に見た場所"
              %br/
              = f.text_field :lost_place, class: "form-control", id: "placeField"
            .form-group
              = f.label :詳細
              %br/
              = f.text_area :detail, class: "form-control", rows: 3, id: "detailField"
            .form-group
              = f.label :"地図"
              %br/
              = f.text_field :latitude, class: "form-control d-none", id: "latitudeField"
              = f.text_field :longitude, class: "form-control d-none", id: "longitudeField"
              %input#search-box.form-control{type: "text"}
            #map.mb-4{"data-latitude": @post.latitude, "data-longitude": @post.longitude}
            .form-group
              = f.submit "張り紙をする", class: "btn btn-primary btn-block btn-lg", type: "button", id: "postSubmitButton"
  }
  = render "trim"

app/views/posts/index.html.haml
= render "/layouts/navbar"
.bg-image.bg-gray-wall
  .container.container__main
    .row
      .col-lg-12.mt-4
        .row
          = render @posts
    .footer.fixed-bottom
      .container
        = button_to "張り紙をする", new_post_path, method: :get, class: "nav-item btn btn-primary mb-2 mr-2 float-right"

app/views/posts/index.js.erb
$(function () {
  console.log('index loaded');
});

$(document).on('turbolinks:load', function(){
  console.log('index loaded');
});

app/views/posts/new.html.haml
= render "/layouts/navbar"
.bg-image.bg-gray-wall
  .container.container__main{"data-controller": controller_name, "data-action": action_name}
    .row
      .col-md-8.mx-auto
        .card.my-3.bg-paper
          .card-body
            %h1.text-center 張り紙
            %hr
            - if @post.errors.any?
              .alert.alert-primary.pt-0
                %ul
                - @post.errors.full_messages.each do |message|
                  %li= message
            = form_with model: @post, id: "postForm" do |f|
              .form-group
                = f.label :タイトル
                %br/
                = f.text_field :title, class: "form-control", id: "titleField"
              .image-box.text-center.mb-2
                = image_tag "cat_default.png", class: "img-thumbnail"
                .image-mask
                  = image_tag "no_image_small.png"
              .form-group.d-none
                = f.label :お写真
                %br/
                = f.file_field :image, class: "form-control-file", id: "imageFile"
              .form-group
                = f.label :お名前
                %br/
                = f.text_field :name, class: "form-control", id: "nameField"
              .form-group
                = f.label :"いなくなった場所・最後に見た場所"
                %br/
                = f.text_field :lost_place, class: "form-control", id: "placeField"
              .form-group
                = f.label :詳細
                %br/
                = f.text_area :detail, class: "form-control", rows: 3, id: "detailField"
              .form-group
                = f.label :"地図"
                %br/
                = f.text_field :latitude, class: "form-control d-none", id: "latitudeField"
                = f.text_field :longitude, class: "form-control d-none", id: "longitudeField"
                %input#search-box.form-control{type: "text"}
              #map.mb-4
              .form-group
                = f.submit "張り紙をする", class: "btn btn-primary btn-block btn-lg", id: "postSubmitButton", type: "button"
        = render "trim"

app/views/posts/show.html.haml
= render "/layouts/navbar"
.bg-gray-wall
  .container.container__main
    .row
      .col-12.col-lg-8.mx-auto.my-5
        .card.bg-paper
          .card-body
            %h1.card-title.text-center.mb-3.text-danger= @post.title
            - if @post.image.present?
              = image_tag @post.image.url, class: "img-thumbnail", "data-lat": @post.latitude, "data-lng": @post.longitude
              .card-text.mt-2
                .row.mb-3
                  .col-4.col-md-3
                    %h5 場所:
                    %h5 お名前:
                    %h5 いつから:
                    %h5 詳細:
                    %h5 地図:
                  .col-8.col-md-8
                    %h5= @post.lost_place
                    %h5= @post.name
                    %h5= @post.lost_date.strftime("%Y年 %-m月 %-d日")
                    %p= @post.detail
                = button_to "近くの情報を探す", post_path(@post), {remote: true, method: :get, "data-type": "json", format: "json", class: "btn btn-primary mb-2", id: "geo-search"}
                #map.mb-2{"data-latitude": @post.latitude, "data-longitude": @post.longitude}
              - if user_signed_in? && current_user.id == @post.user_id
                = link_to "編集", edit_post_path(@post), class: "card-link"
                = link_to "削除", "/posts/#{@post.id})", method: :delete, class: "card-link"

app/views/posts/show.js.erb
$(function () {
  $(document).on('ajax:success', ".button_to", function(event) {
    console.log('show.js');
    $("#map").empty();
    var markers = [];
    var marker;
    var bounds = new google.maps.LatLngBounds();
    var position = {lat: $(".img-thumbnail").data('lat'), lng: $(".img-thumbnail").data('lng')};
    // var position = map.getCenter();
    console.log(position);
    var map = new google.maps.Map($("#map")[0], {center: position, zoom: 14});

    marker = new google.maps.Marker({position: position, map: map, draggable: true});



    var postInfo = "<div class-marker-info'>"+ "<h6 class='m-0'><center>YOU</center></h6>" + "<%= escape_javascript(image_tag @post.image.url, size: '120x120', class: 'img-thumbnail') %>" + "</div>";

    var infowindow = new google.maps.InfoWindow({content: postInfo});
    infowindow.open(map, marker);
    marker.addListener('dragend', function(e){
      map.panTo(e.latLng);
      $("#latitudeField").val(e.latLng.lat);
      $("#longitudeField").val(e.latLng.lng);
    });

    marker.addListener('click', function(e){
      infowindow.open(map, this);
    });
    markers.push(marker);
    // bounds.extend (marker.position);

    <% @sightings.each do |sighting| %>
      marker = new google.maps.Marker({map: map, draggable: true});
      marker.setPosition({lat: <%= sighting.latitude%>, lng: <%= sighting.longitude%>});

      var postInfo = "<div class-marker-info'>"

      + "<%= escape_javascript(link_to image_tag(sighting.image.url, size: '100x100', class: 'img-thumbnail'), sighting_path(sighting)) %>"
      + "</div>";

      addListenerToMarker(marker, postInfo);
      // bounds.extend (marker.position);
      markers.push(marker);
    <% end %>

    // map.fitBounds (bounds);

  });

  $(document).on('ajax:complete', ".button_to", function(event) {
    console.log('complete');
  });

  function addListenerToMarker(m_marker, m_info) {
    m_marker.addListener('dragend', function(e){
      map.panTo(e.latLng);
      $("#latitudeField").val(e.latLng.lat);
      $("#longitudeField").val(e.latLng.lng);
    });

    var infowindow = new google.maps.InfoWindow({content: m_info});
      infowindow.open(map, m_marker);

    m_marker.addListener('click', function(e){
      infowindow.open(map, this);
    });
  }
});

app/views/sightings/_sighting.html.haml
.col-lg-4.col-md-6.mb-4{id: "sightingContainer-#{sighting.id}"}
  .card.bg-paper.sighting__summary
    = image_tag sighting.image.url, class: "card-img-top"
    .card-body.sighting__summary__body
      .dropdown
      = link_to "", "",role: "button", class: "dropdown-toggle icon fa-cog text-gray sighting__summary__body__dropdown", id: "drpodownMenulink", "data-toggle": "dropdown", "aria-haspopup": true, "aria-expanded": false
      .dropdown-menu-right.dropdown-menu{"aria-labelledby": "dropdownMenuLink"}
        = link_to "詳細", sighting_path(sighting), class: "dropdown-item"
        - if current_user.id == sighting.user_id
          = link_to "削除", "/sightings/#{sighting.id}", class: "dropdown-item delete", method: :delete, remote: true, format: "json", "data-type": "json"
      %p.m-0 場所: #{sighting.place}
      %p.m-0 #{sighting.date.strftime("%Y年 %-m月 %-d日")}

app/views/sightings/destroy.js.erb
$(function(){
  $(document).on('ajax:complete', '.delete', function(event) {
    event.preventDefault();
    /* Act on the event */
    console.log('destroy');
  });
});

app/views/sightings/index.html.haml
= render "/layouts/navbar"
.bg-image--wood
  .container-fruid.search.bg-light
    .container
      .row
        .col-lg-8.mx-auto
          .search-box.my-3
            = form_with model: Sighting.new, method: :get, class: "search__form" do |f|
              = f.text_field :keyword, class: "form-control my-3 search__form__input", required: true
              //= f.collection_check_boxes :sightings, Sightings.all
              = f.submit "検索", class: "btn btn-primary btn-block search__form__submit"
  .bg-wood
    .container.container__search-result
      .row
        .col-lg-12.mt-4
          .row#search-result
      .footer.fixed-bottom
        .container
          = button_to "情報提供する", new_sighting_path, method: :get, class: "nav-item btn btn-primary mb-2 mr-2 float-right"

app/views/sightings/index.js.erb
$(function(){
  $(document).on("ajax:success", ".search__form", function(event) {
    console.log('index.js.erb');

    $("#search-result").html(event.detail[2].response);
  });
});

app/views/sightings/new.html.haml
= render "/layouts/navbar"
.bg-image.bg-wood
  .container.container__main
    .row
      .col-lg-6.col-md-8.mx-auto
        .card.my-3.bg-paper
          .card-body
            %h1.text-center 目撃情報
            %hr
            = form_with model: Sighting.new, id: "sightingForm" do |f|
              .image-box.text-center.mb-2
                = image_tag "cat_default.png", class: "img-thumbnail"
                .image-mask
                  = image_tag "no_image_small.png"
              .form-group.hidden.d-none
                = f.label :写真
                %br/
                = f.file_field :image, class: "form-control-file", id: "imageFile", autofocus: true
              .form-group
                = f.label :"みかけた場所"
                %br/
                = f.text_field :place, class: "form-control", id: "placeField"
              .form-group
                = f.label :詳細
                %br/
                = f.text_area :detail, class: "form-control", rows: 4, id: "detailField"
              .form-group
                = f.label :"地図"
                %br/
                -# = f.label :"address"
                -# = f.text_field :address, class: "form-control", id: "addressField"
                = f.label :"latitude(debug)"
                = f.text_field :latitude, class: "form-control", id: "latitudeField"
                = f.label :"longitude(debug)"
                = f.text_field :longitude, class: "form-control", id: "longitudeField"
                %br/
                %input#search-box.form-control{type: "text"}
              #map.mb-4{"data-location": ""}
              .form-group
                = f.submit "情報提供する", id: "sightingSubmitButton", class: "btn btn-primary btn-block btn-lg", type: "button"
        = render "/posts/trim"

app/views/sightings/show.html.haml
= render "/layouts/navbar"
.bg-wood
  .container.container__main
    .row
      .col-12.col-lg-8.mx-auto.my-5
        .card.bg-paper
          .card-body
            - if @sighting.image.present?
              = image_tag @sighting.image.url, class: "img-thumbnail", "data-lat": @sighting.latitude, "data-lng": @sighting.longitude
            %p.mt-3 場所: #{@sighting.place}
            %p 詳細:
            %p.card-text #{@labels}

app/views/users/show.html.haml
= render "/layouts/navbar"
.bg-image.bg-wallpaper
  .mypage.container-fruid.container__main{"data-controller": controller_name, "data-action": action_name}
    .sidebar.bg-light.mypage__sidebar
      .sidebar-sticy.mypage__sidebar__content
        %ul.nav.flex-column.sidebar__list
          %li.nav-item.sidebar__list__item
            = link_to "あなたの張り紙", "/users/#{current_user.id}/posts", id: "postsLink", class: "nav-link icon far fa-file", remote: true
          %li.nav-item.sidebar__list__item
            = link_to "あなたの目撃情報", "/users/#{current_user.id}/sightings", id: "sightingsLink", class: "nav-link icon fas fa-eye", remote: true
            - # fa_icon "eye", text: "あなたの目撃情報"
    .mypage__main-content
      .content.p-4
        .row.mypage__result